version: "3"
services:
  hub: 
    image: selenium/hub:3.141.59
    ports: 
        - "4444:4444"
      
  chrome:
    image: selenium/node-chrome:3.141.59
    #shm_size = shared memory size
    shm_size: '1gb'
    environment: 
        - HUB_HOST=hub
    depends_on: 
        - hub
        
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '1gb'
    environment: 
        - HUB_HOST=hub
    depends_on:
        - hub
  flights-chrome:
    image: surajitsarkarofficial/flight-tests
    depends_on:
        - chrome
        - firefox
    environment:
        - BROWSER=chrome
        - MODULE=flightTests.xml
        - HUB_HOST=hub
    volumes:
        - ./flight-chrome-tests-output:/usr/share/udemy/test-output
  flights-firefox:
    image: surajitsarkarofficial/flight-tests
    depends_on:
        - chrome
        - firefox
    environment:
        - BROWSER=firefox
        - MODULE=flightTests.xml
        - HUB_HOST=hub
    volumes:
        - ./flight-firefox-tests-output:/usr/share/udemy/test-output